name: Tests

on:
  push:
    branches:
      - fam
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v1
      - name: Install dependencies
        run: uv sync --extra dev
      - name: Run unit tests
        run: uv run pytest
